Added New Folder for EPS Schematics
Added New Folder for EPS Schematics as EPS will have it's own board. Currently running through the compiled errors on the schematic.

List of error editing I have done so far:

Folder: eps_6.0.SchDoc
Error: Net 3V3VOUT1 contains multiple Output Sheet Entrys (Sheet Entry U_eps_bb2-3V3VOUT2(Output))
Description: There are multiple outputs sheets with one input. (No 1:1 relationship between input and output) (Could that be dangerous?)
Fix: I assumed that this schematic is correct, I added a no ERC directive

Error: Net VOLT5VA contains multiple Output Sheet Entrys (Sheet Entry U_eps_bt2-VOLT5VB(Output))
Description: There are multiple outputs sheets with one input.
Fix: I assumed that this schematic is correct, I added a no ERC directive

Error: Sheet-Entry 3V3VOUT2 not matched to Port at 5000mil,5400mil
Description: No matching port
Fix: I added a 3V3OUT2 port along with resistors and capacitors that mimics bb1’s schematic. I haven’t placed the resistor numbers or footprints yet

Other errors:
Sheet-Entry BB1_EN not matched to Port at 2000mil,3600mil
BB2
BT1
BT2

Since Mitchell hasn’t done those parts yet.